from yacs.config import CfgNode

_C = CfgNode()
_C.TRAIN_DIR = None
_C.VAL_DIR = None
_C.DEVICE = 'cuda:0'
'''old'''
# _C.N_HIS = 5
# _C.ROLLOUT_STEPS = 0
'''new'''
_C.N_HIS = 6
_C.ROLLOUT_STEPS = 601
_C.PRED_STEPS = 1
_C.DATASET_ABS = None
_C.MAX_TEST = 0
_C.MAX_VAL = 0
_C.MAX_TRAIN = 0
_C.KINEMATIC_PARTICLE_ID = 3
_C.NUM_PARTICLE_TYPES = 9
_C.NUM_PARTICLE_FEATURE = 0
_C.TRAIN_INTERVAL = 1

_C.SOLVER = CfgNode()
_C.SOLVER.BASE_LR = 0.001
_C.SOLVER.MIN_LR = 0.0
_C.SOLVER.VAL_INTERVAL = 1
_C.SOLVER.GRAD_ACCUMULATION_STEP = 8
_C.SOLVER.FAST_VAL_EPOCH = 5
_C.SOLVER.FAST_VAL_INTERVAL = 1000
_C.SOLVER.WEIGHT_DECAY = 0.0
_C.SOLVER.LOSS = 'Acc'
_C.SOLVER.WARMUP_ITERS = -1
_C.SOLVER.MAX_ITERS = 150
_C.SOLVER.TIRED_ITERS = 3
_C.SOLVER.TRAIN_SHUFFLE = 1
_C.SOLVER.BATCH_SIZE = 128
_C.SOLVER.VAL_BATCH_SIZE = 1
_C.SOLVER.LR_DECAY_INTERVAL = 5e6
_C.SOLVER.WEIGHT_C = 5.0
_C.SOLVER.LAMBDA = 0.01

_C.NET = CfgNode()
_C.NET.RADIUS = 0.
_C.NET.NOISE = 0.
_C.NET.MAX_EDGE_PER_PARTICLE = 150
_C.NET.SELF_EDGE = False
_C.NET.HIDDEN_SIZE = 64
_C.NET.PARTICLE_TYPE_EMB_SIZE = 16
_C.NET.EDGE_TYPE_EMB_SIZE = 16
_C.NET.DIRECTION_TYPE_EMB_SIZE = 16
_C.NET.GNN_LAYER = 10


