DATASET_ABS: 'SlideSameRDataset'
TRAIN_DIR: 'Slide_Same_R/train'
VAL_DIR: 'Slide_Same_R/valid'
DEVICE: 'cuda:1'
ROLLOUT_STEPS: 20
N_HIS: 2
PRED_STEPS: 1
MAX_TEST: 101
MAX_VAL: 199
MAX_TRAIN: 700
KINEMATIC_PARTICLE_ID: 0
NUM_PARTICLE_TYPES: 3
TRAIN_INTERVAL: 1

SOLVER:
  BASE_LR: 1.0e-5
  MIN_LR: 1.0e-6
  LR_DECAY_INTERVAL: 5e7
  WEIGHT_DECAY: 0.0
  LOSS: 'Acc'
  MAX_ITERS: 200
  TIRED_ITERS: 800
  WARMUP_ITERS: 0
  GRAD_ACCUMULATION_STEP: 1
  VAL_INTERVAL: 2000
  FAST_VAL_EPOCH: 30
  FAST_VAL_INTERVAL: 1000
  TRAIN_SHUFFLE: 1
  BATCH_SIZE: 1
  VAL_BATCH_SIZE: 1
  WEIGHT_C: 5.0
  LAMBDA: 1.0e+0

NET:
  NOISE: 0.00067
  RADIUS: 20.0
  MAX_EDGE_PER_PARTICLE: 20
  SELF_EDGE: True
  HIDDEN_SIZE: 256
  PARTICLE_TYPE_EMB_SIZE: 16
  EDGE_TYPE_EMB_SIZE: 16
  DIRECTION_TYPE_EMB_SIZE: 16
  GNN_LAYER: 10

